Генерация исключений - механизм обработки ошибок, который позволяет программам безопасно обрабатывать ошибки без прерывания работы всего приложения. Когда происходит ошибка, программа генерирует исключение, которое может быть обработано с помощью блока try - catch. Блок try-catch указывает, какие участки кода могут генерировать исключения, и как эти исключения должны быть обработаны. Если исключение не обрабатывается в блоке catch, оно может распространиться на более высокий уровень стека вызовов, пока не достигнет функции main, которая в этом случае аварийно завершится.
```c++
#include <iostream>

using namespace std;

void Foo(int value) {
	if (value < 0) {
		throw runtime_error("Число меньше 0");
	}
	cout << "Перменная = " << value << endl;
}

int main() {
	try {
		Foo(-55);
	}
	catch (const exception & ex) {
		cout << "Мы поймали " << ex.what() << endl;
	}
	return 0;
}
```

[[C++]] [[Исключения]] [[try catch]]